version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: employee_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employee_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    container_name: employee_web
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql+pymysql://root:password@mysql/employee_db
      # Uncomment below to override default Flask settings
      # FLASK_ENV: production
      # FLASK_APP: src:create_app
      # PYTHONPATH: /app
      # GUNICORN_WORKERS: 4
      # GUNICORN_LOG_LEVEL: info
      PORT: 5000
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  mysql_data:
# docker tag microservice-web:latest rajeshupadhayaya/nagarro:latest
