apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: web   
    type: database-tier 
spec:
  selector:
    matchLabels:
      app: db
      type: mysql
  template:
    metadata: 
      name: database
      labels:
        app: db
        type: mysql
    spec:
      containers:
        - name: mysql-db
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: employee-web-config
                  key: MYSQL_DATABASE
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql-volume 
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: web-disk

---
apiVersion: v1
kind: Service
metadata:
  name: db-clusterip-service
  labels:
    app: database-ip
    type: cluster-ip
spec:
  type: ClusterIP
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    app: db
    type: mysql
