apiVersion: v1
kind: Pod
metadata: 
  name: database
  labels:
    app: db
spec:
  containers:
    - name: mysql-db
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: employee-web-config
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: employee-web-config
              key: MYSQL_DATABASE
      volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-volume 
  volumes:
    - name: mysql-volume
      persistentVolumeClaim:
        claimName: web-disk